[project]
name = "fast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "strawhat8", email = "koushikreddychencharapu@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi>=0.141.1",
    "fastapi-users[sqlalchemy]>=15.0.5",
    "imagekitio>=5.10.0",
    "python-dotenv>=1.2.3",
    "streamlit>=1.39.0",
    "uvicorn[standard]>=0.54.0",
]

[project.scripts]
fast = "fast:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
